project_id = "gwuyvnzojocfebypqfff"

[functions.pagarme-webhook]
verify_jwt = false

[functions.pagarme-checkout]
verify_jwt = true

[functions.evolution-api]
verify_jwt = true

[functions.evolution-webhook]
verify_jwt = false

[functions.sync-agent-n8n]
verify_jwt = true

[functions.google-calendar-oauth]
verify_jwt = false

[functions.test-followup]
verify_jwt = false

[functions.send-followup]
verify_jwt = false
