project_id = "gwuyvnzojocfebypqfff"

[functions.pagarme-webhook]
verify_jwt = false

[functions.pagarme-checkout]
verify_jwt = true

[functions.evolution-api]
verify_jwt = true

[functions.evolution-webhook]
verify_jwt = false
